### ISSUE TITLE
Shiny Mewtwo is not flagged as having a mega evolution

### ISSUE THREAD

**Issue by Manitary** [Chupalika/SobbleDex#16]
In the following example, Shiny Mewtwo should appear in the list

![image](https://github.com/Chupalika/SobbleDex/assets/11020501/571896a8-c84d-4ac4-9bbc-f94eed534154)

**Comment by Manitary** [comment]
At first glance I believe the issue may be [here](https://github.com/Chupalika/SobbleDex/blob/2da83c21ace6af0f68be5cee627a244b72615416/shuffle_commands.py#L908) since other shiny mega do not have the same problem, and neither does Charizard (the only other one with two mega evo), but I did not test it yet.

**Comment by Chupalika** [comment]
fixed, thanks!
